sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_4297e941f9f4_key -iv $encrypted_4297e941f9f4_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.clud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
